apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: front-final-job-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: mehdi-chebbi/front-final-job
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: front-final-job-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: front-final-job-runner
  scaleUpTriggers:
    - amount: 1
      duration: 5m
  minReplicas: 1
  maxReplicas: 3
